kind: ConfigMap
apiVersion: v1
metadata: # kpt-merge: kube-system/multus-daemon-config
  name: multus-daemon-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|kube-system|multus-daemon-config'
data:
  daemon-config.json: |-
    {
        "chrootDir": "/hostroot",
        "confDir": "/host/etc/cni/net.d",
        "logLevel": "verbose",
        "socketDir": "/host/run/multus/",
        "cniVersion": "0.3.1",
        "cniConfigDir": "/host/etc/cni/net.d",
        "multusConfigFile": "auto",
        "multusAutoconfigDir": "/host/etc/cni/net.d"
    }
