apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata: # kpt-merge: /propagate-namespace
  name: propagate-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|ApplyReplacements|default|propagate-namespace'
replacements:
- source:
    kind: ConfigMap
    name: namespace
    fieldPath: data.namespace
  targets:
  - select:
      kind: Namespace
    fieldPaths:
    - metadata.name
  - select:
      kind: Capacity
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]
  - select:
      kind: NFConfig
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]
    - metadata.namespace
  - select:
      kind: NFDeployment
    fieldPaths:
    - metadata.namespace
    - metadata.annotations.[specializer.nephio.org/namespace]
  - select:
      kind: NetworkAttachmentDefinition
    fieldPaths:
    - metadata.namespace
    - metadata.annotations.[specializer.nephio.org/namespace]
